name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Create config.json
        run: |
          mkdir -p public
          echo '{
            "FIREBASE_API_KEY": "${{ secrets.FIREBASE_API_KEY }}",
            "FIREBASE_AUTH_DOMAIN": "${{ secrets.AUTH_DOMAIN }}",
            "FIREBASE_PROJECT_ID": "${{ secrets.FIREBASE_PROJECT_ID }}",
            "FIREBASE_STORAGE_BUCKET": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            "FIREBASE_MESSAGING_SENDER_ID": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            "FIREBASE_APP_ID": "${{ secrets.FIREBASE_APP_ID }}",
            "FIREBASE_MEASUREMENT_ID": "${{ secrets.FIREBASE_MEASUREMENT_ID }}",
            "STRIPE_PUBLISHABLE_KEY": "${{ secrets.STRIPE_PUBLISHABLE_KEY }}"
          }' > public/config.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
