name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js (opcional)
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Create config.json with secrets
        run: >
          mkdir -p public

          cat > public/config.json <<EOL

          {
            "FIREBASE_API_KEY": "${{ secrets.FIREBASE_API_KEY }}",
            "FIREBASE_AUTH_DOMAIN": "${{ secrets.AUTH_DOMAIN }}",
            "FIREBASE_PROJECT_ID": "${{ secrets.FIREBASE_PROJECT_ID }}",
            "FIREBASE_STORAGE_BUCKET": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            "FIREBASE_MESSAGING_SENDER_ID": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            "FIREBASE_APP_ID": "${{ secrets.FIREBASE_APP_ID }}",
            "FIREBASE_MEASUREMENT_ID": "${{ secrets.FIREBASE_MEASUREMENT_ID }}",
            "STRIPE_PUBLISHABLE_KEY": "${{ secrets.STRIPE_PUBLISHABLE_KEY }}"
          }

          EOL
      - name: Build static files
        id: build
        run: >
          # Aquí va el comando para construir los archivos estáticos de tu sitio
          (como `npm run build` o cualquier otro que uses)

          # Dependiendo de cómo construyas tu sitio HTML + JS
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
