name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if required)
        uses: actions/setup-node@v3
        with:
          node-version: 16
        if: needs('build') # Only run if the 'build' job succeeds

      - name: Build (if required)
        id: build
        uses: actions/setup-node@v3
        with:
          node-version: 16
        run: |
          npm install
          npm run build
        if: contains(github.event.head_commit.message, 'deploy') # Only build if 'deploy' is in the commit message

      - name: Create config.json with secrets
        run: |
          mkdir -p public
          echo '{
            "FIREBASE_API_KEY": "${{ secrets.FIREBASE_API_KEY }}",
            "FIREBASE_AUTH_DOMAIN": "${{ secrets.AUTH_DOMAIN }}",
            "FIREBASE_PROJECT_ID": "${{ secrets.FIREBASE_PROJECT_ID }}",
            "FIREBASE_STORAGE_BUCKET": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            "FIREBASE_MESSAGING_SENDER_ID": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            "FIREBASE_APP_ID": "${{ secrets.FIREBASE_APP_ID }}",
            "FIREBASE_MEASUREMENT_ID": "${{ secrets.FIREBASE_MEASUREMENT_ID }}",
            "STRIPE_PUBLISHABLE_KEY": "${{ secrets.STRIPE_PUBLISHABLE_KEY }}"
          }' > public/config.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
