name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js (opcional)
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Create config.json with secrets
        run: >
          mkdir -p public

          cat > public/config.json <<EOL

          {
            "FIREBASE_API_KEY": "${{ secrets.FIREBASE_API_KEY }}",
            "FIREBASE_AUTH_DOMAIN": "${{ secrets.AUTH_DOMAIN }}",
            "FIREBASE_PROJECT_ID": "${{ secrets.FIREBASE_PROJECT_ID }}",
            "FIREBASE_STORAGE_BUCKET": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            "FIREBASE_MESSAGING_SENDER_ID": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            "FIREBASE_APP_ID": "${{ secrets.FIREBASE_APP_ID }}",
            "FIREBASE_MEASUREMENT_ID": "${{ secrets.FIREBASE_MEASUREMENT_ID }}",
            "STRIPE_PUBLISHABLE_KEY": "${{ secrets.STRIPE_PUBLISHABLE_KEY }}"
          }

          EOL
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: public
      - name: Publish to GitHub Pages
        uses: actions/deploy-pages@v1
