name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Configurar archivo config.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
        run: |
          echo "window.FIREBASE_CONFIG = JSON.parse('${FIREBASE_CONFIG}');" > public/config.js
          echo "window.STRIPE_PUBLIC_KEY = '${STRIPE_PUBLISHABLE_KEY}';" >> public/config.js

      - name: Verificar contenido del directorio público
        run: ls -R public/

      - name: Autenticar con Firebase
        run: firebase auth:login:ci --token "${{ secrets.FIREBASE_AUTH_TOKEN }}"

      - name: Deploy a Firebase Hosting
        run: firebase deploy --only hosting
